module.exports = [
    {
       "name":"Google",
       "billables":[
          {
             "id":"1",
             "project":"Google",
             "date":"01/07/2019",
             "start_time":"9:00",
             "end_time":"17:00",
             "unit_price":300,
             "hours":16,
             "total_cost":4800
          },
          {
             "id":"3",
             "project":"Google",
             "date":"01/07/2019",
             "start_time":"10:00",
             "end_time":"15:00",
             "unit_price":50,
             "hours":5,
             "total_cost":250
          }
       ]
    },
    {
       "name":"Facebook",
       "billables":[
          {
             "id":"1",
             "project":"Facebook",
             "date":"01/07/2019",
             "start_time":"9:00",
             "end_time":"17:00",
             "unit_price":200,
             "hours":8,
             "total_cost":1600
          },
          {
             "id":"2",
             "project":"Facebook",
             "date":"01/07/2019",
             "start_time":"11:00",
             "end_time":"16:00",
             "unit_price":100,
             "hours":5,
             "total_cost":500
          }
       ]
    }
 ]