image: node:11.7.0

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

stages:
  - build
  - tests
  - lints
  - openMr
  - production

Build:
  stage: build
  before_script:
    - rm -rf node_modules
    - yarn config set cache-folder .yarn
    - yarn install
  artifacts:
    paths:
      - node_modules/
  script:
    - npm run build

Run Frontend Tests:
  stage: tests
  script:
    - npm run test:frontend

Run Backend Tests:
  stage: tests
  script:
    - npm run test:backend

Run Vulnerability Test:
  stage: tests
  script:
    - npm run synk
  
Run All Lints:
  stage: lints
  script:
    - npm run lint

Open Merge Request:
  stage: openMr
  before_script: [] # We do not need any setup work,removing the global one
  only:
    - /^(feature|issue)\/*/ # Strict naming convention
  script:
    - bash ./.gitlab-deploy/auto-merge-request.sh

Deploy to Production:
  stage: production
  before_script:
    - mkdir -p ~/.ssh
    - echo -e "$PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash ./.gitlab-deploy/gitlab-deploy.prod.sh
  #environment:
    #name: production
    #url: https://liveurl.com # Exposes a button that when clicked take you to the defined URL:
  only:
    - master
  #when: manual # Should we choose to manually deploy